# Generated by Django 4.2.16 on 2025-04-18 23:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0002_galleryimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['-created'], 'verbose_name': 'Gallery Image', 'verbose_name_plural': 'Gallery Images'},
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='gallery/'),
        ),
    ]
