# Generated by Django 4.2.16 on 2025-04-18 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0003_alter_galleryimage_options_galleryimage_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['order', '-created'], 'verbose_name': 'Gallery Image', 'verbose_name_plural': 'Gallery Images'},
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of the image in the gallery'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
