# Generated by Django 4.2.16 on 2025-04-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0004_alter_galleryimage_options_galleryimage_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
