# Generated by Django 4.2.16 on 2025-04-19 06:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nova', '0005_galleryimage_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('product_interest', models.CharField(blank=True, choices=[('novafeed-protein', 'novafeed Protein'), ('ecovita', 'EcoVita'), ('other', 'Other')], max_length=50)),
                ('service_interest', models.CharField(blank=True, choices=[('feasibility', 'Feasibility Studies'), ('technology', 'Technology Transfer'), ('consulting', 'On-site Consulting'), ('data', 'Data-Driven Farming'), ('other', 'Other')], max_length=50)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Enquiry',
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
